import React, { useRef, useState } from 'react';
import { toPng } from 'html-to-image';

interface DailyVibeCardProps {
  sunSign: string;
  moonSign?: string;
  dailyMessage: string;
  luckyNumber: number;
  luckyColor: { name: string; hex: string };
  date?: Date;
}

interface CompatibilityCardProps {
  personA: string;
  personB: string;
  score: number;
  sunSignA: string;
  sunSignB: string;
  headline: string;
}

// Sign emojis
const SIGN_EMOJI: Record<string, string> = {
  Aries: '♈', Taurus: '♉', Gemini: '♊', Cancer: '♋',
  Leo: '♌', Virgo: '♍', Libra: '♎', Scorpio: '♏',
  Sagittarius: '♐', Capricorn: '♑', Aquarius: '♒', Pisces: '♓',
};

export function ShareableDailyCard({ sunSign, moonSign, dailyMessage, luckyNumber, luckyColor, date = new Date() }: DailyVibeCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [downloading, setDownloading] = useState(false);

  const handleDownload = async () => {
    if (!cardRef.current) return;
    setDownloading(true);
    
    try {
      const dataUrl = await toPng(cardRef.current, { 
        quality: 0.95,
        pixelRatio: 2,
      });
      
      const link = document.createElement('a');
      link.download = `astromeric-daily-${date.toISOString().split('T')[0]}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error('Failed to generate image:', err);
    } finally {
      setDownloading(false);
    }
  };

  const handleShare = async () => {
    if (!cardRef.current) return;
    
    try {
      const dataUrl = await toPng(cardRef.current, { quality: 0.95, pixelRatio: 2 });
      const blob = await (await fetch(dataUrl)).blob();
      const file = new File([blob], 'astromeric-daily.png', { type: 'image/png' });
      
      if (navigator.share) {
        await navigator.share({
          title: 'My Daily Cosmic Vibe',
          text: `✨ ${sunSign} Daily Vibe\n${dailyMessage}\n\nGenerated by Astromeric`,
          files: [file],
        });
      }
    } catch (err) {
      console.error('Share failed:', err);
      // Fallback to download
      handleDownload();
    }
  };

  const formattedDate = date.toLocaleDateString('en-US', { 
    weekday: 'long', 
    month: 'long', 
    day: 'numeric' 
  });

  return (
    <div className="shareable-card-wrapper">
      <div ref={cardRef} className="shareable-daily-card">
        <div className="card-bg-pattern" />
        
        <div className="card-header">
          <span className="card-logo">✨ ASTROMERIC</span>
          <span className="card-date">{formattedDate}</span>
        </div>
        
        <div className="card-sign-display">
          <span className="sign-emoji">{SIGN_EMOJI[sunSign] || '⭐'}</span>
          <span className="sign-name">{sunSign}</span>
          {moonSign && <span className="moon-info">🌙 Moon in {moonSign}</span>}
        </div>
        
        <div className="card-message">
          <p>"{dailyMessage}"</p>
        </div>
        
        <div className="card-lucky-items">
          <div className="lucky-item">
            <span className="lucky-icon">🔢</span>
            <span className="lucky-value">{luckyNumber}</span>
          </div>
          <div className="lucky-item">
            <span 
              className="lucky-color-swatch" 
              style={{ backgroundColor: luckyColor.hex }}
            />
            <span className="lucky-value">{luckyColor.name}</span>
          </div>
        </div>
        
        <div className="card-footer">
          <span>astromeric.app</span>
        </div>
      </div>
      
      <div className="share-actions">
        <button 
          className="share-btn download"
          onClick={handleDownload}
          disabled={downloading}
        >
          {downloading ? '⏳' : '📥'} Download
        </button>
        <button 
          className="share-btn share"
          onClick={handleShare}
        >
          📤 Share
        </button>
      </div>
      
      <style>{`
        .shareable-card-wrapper {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 1rem;
        }
        
        .shareable-daily-card {
          width: 350px;
          padding: 1.5rem;
          background: linear-gradient(135deg, #0b0c15 0%, #1a1f2e 50%, #0b0c15 100%);
          border-radius: 20px;
          border: 2px solid rgba(136, 192, 208, 0.3);
          position: relative;
          overflow: hidden;
          color: #eceff4;
        }
        
        .card-bg-pattern {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background-image: radial-gradient(circle at 20% 80%, rgba(136, 192, 208, 0.1) 0%, transparent 50%),
                            radial-gradient(circle at 80% 20%, rgba(191, 97, 106, 0.1) 0%, transparent 50%);
          pointer-events: none;
        }
        
        .card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1.5rem;
          position: relative;
          z-index: 1;
        }
        
        .card-logo {
          font-size: 0.8rem;
          font-weight: 600;
          letter-spacing: 1px;
          color: #88c0d0;
        }
        
        .card-date {
          font-size: 0.75rem;
          color: #81a1c1;
        }
        
        .card-sign-display {
          text-align: center;
          margin-bottom: 1.5rem;
          position: relative;
          z-index: 1;
        }
        
        .sign-emoji {
          font-size: 3.5rem;
          display: block;
          margin-bottom: 0.5rem;
        }
        
        .sign-name {
          font-size: 1.5rem;
          font-weight: 700;
          display: block;
          margin-bottom: 0.25rem;
        }
        
        .moon-info {
          font-size: 0.85rem;
          color: #81a1c1;
        }
        
        .card-message {
          background: rgba(0, 0, 0, 0.3);
          padding: 1.25rem;
          border-radius: 12px;
          margin-bottom: 1.5rem;
          position: relative;
          z-index: 1;
        }
        
        .card-message p {
          margin: 0;
          font-style: italic;
          line-height: 1.6;
          text-align: center;
          font-size: 0.95rem;
        }
        
        .card-lucky-items {
          display: flex;
          justify-content: center;
          gap: 2rem;
          margin-bottom: 1.5rem;
          position: relative;
          z-index: 1;
        }
        
        .lucky-item {
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }
        
        .lucky-icon {
          font-size: 1.25rem;
        }
        
        .lucky-color-swatch {
          width: 20px;
          height: 20px;
          border-radius: 50%;
          border: 2px solid rgba(255, 255, 255, 0.3);
        }
        
        .lucky-value {
          font-weight: 500;
        }
        
        .card-footer {
          text-align: center;
          font-size: 0.7rem;
          color: #4c566a;
          position: relative;
          z-index: 1;
        }
        
        .share-actions {
          display: flex;
          gap: 0.75rem;
        }
        
        .share-btn {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          padding: 0.75rem 1.25rem;
          border-radius: 8px;
          font-size: 0.9rem;
          cursor: pointer;
          transition: transform 0.2s, box-shadow 0.2s;
        }
        
        .share-btn:hover:not(:disabled) {
          transform: translateY(-2px);
        }
        
        .share-btn:disabled {
          opacity: 0.7;
          cursor: not-allowed;
        }
        
        .share-btn.download {
          background: rgba(136, 192, 208, 0.2);
          color: #88c0d0;
          border: 1px solid #88c0d0;
        }
        
        .share-btn.share {
          background: #88c0d0;
          color: #0b0c15;
          border: none;
        }
      `}</style>
    </div>
  );
}

export function ShareableCompatCard({ personA, personB, score, sunSignA, sunSignB, headline }: CompatibilityCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [downloading, setDownloading] = useState(false);

  const handleDownload = async () => {
    if (!cardRef.current) return;
    setDownloading(true);
    
    try {
      const dataUrl = await toPng(cardRef.current, { 
        quality: 0.95,
        pixelRatio: 2,
      });
      
      const link = document.createElement('a');
      link.download = `astromeric-compatibility-${personA}-${personB}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error('Failed to generate image:', err);
    } finally {
      setDownloading(false);
    }
  };

  const getScoreColor = () => {
    if (score >= 80) return '#4ade80';
    if (score >= 60) return '#facc15';
    if (score >= 40) return '#f97316';
    return '#ef4444';
  };

  return (
    <div className="shareable-card-wrapper">
      <div ref={cardRef} className="shareable-compat-card">
        <div className="card-bg-pattern" />
        
        <div className="card-header">
          <span className="card-logo">💕 ASTROMERIC</span>
        </div>
        
        <div className="compat-display">
          <div className="person-circle">
            <span className="person-sign">{SIGN_EMOJI[sunSignA] || '⭐'}</span>
            <span className="person-name">{personA}</span>
          </div>
          
          <div className="score-circle" style={{ borderColor: getScoreColor() }}>
            <span className="score-value" style={{ color: getScoreColor() }}>{score}%</span>
          </div>
          
          <div className="person-circle">
            <span className="person-sign">{SIGN_EMOJI[sunSignB] || '⭐'}</span>
            <span className="person-name">{personB}</span>
          </div>
        </div>
        
        <div className="compat-headline">
          <p>"{headline}"</p>
        </div>
        
        <div className="card-footer">
          <span>astromeric.app</span>
        </div>
      </div>
      
      <div className="share-actions">
        <button 
          className="share-btn download"
          onClick={handleDownload}
          disabled={downloading}
        >
          {downloading ? '⏳' : '📥'} Download
        </button>
      </div>
      
      <style>{`
        .shareable-compat-card {
          width: 400px;
          padding: 1.5rem;
          background: linear-gradient(135deg, #0b0c15 0%, #1a1f2e 50%, #0b0c15 100%);
          border-radius: 20px;
          border: 2px solid rgba(191, 97, 106, 0.3);
          position: relative;
          overflow: hidden;
          color: #eceff4;
        }
        
        .shareable-compat-card .card-bg-pattern {
          background-image: radial-gradient(circle at 0% 50%, rgba(191, 97, 106, 0.15) 0%, transparent 50%),
                            radial-gradient(circle at 100% 50%, rgba(191, 97, 106, 0.15) 0%, transparent 50%);
        }
        
        .compat-display {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 1rem;
          margin: 1.5rem 0;
          position: relative;
          z-index: 1;
        }
        
        .person-circle {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 0.5rem;
        }
        
        .person-sign {
          font-size: 2.5rem;
        }
        
        .person-name {
          font-size: 0.9rem;
          font-weight: 500;
          max-width: 80px;
          text-align: center;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        
        .score-circle {
          width: 80px;
          height: 80px;
          border-radius: 50%;
          border: 4px solid;
          display: flex;
          align-items: center;
          justify-content: center;
          background: rgba(0, 0, 0, 0.5);
        }
        
        .score-value {
          font-size: 1.5rem;
          font-weight: 700;
        }
        
        .compat-headline {
          background: rgba(0, 0, 0, 0.3);
          padding: 1rem;
          border-radius: 12px;
          margin-bottom: 1rem;
          position: relative;
          z-index: 1;
        }
        
        .compat-headline p {
          margin: 0;
          font-style: italic;
          line-height: 1.5;
          text-align: center;
          font-size: 0.9rem;
        }
      `}</style>
    </div>
  );
}
