import { jsPDF } from 'jspdf';
import type { PredictionData } from '../types';

/**
 * Generate and download a PDF reading without storing user data.
 * All processing happens client-side in memory.
 */
export function downloadReadingPdf(data: PredictionData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // Helper to add text with word wrap
  const addText = (text: string, fontSize: number, isBold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, contentWidth);
    
    // Check if we need a new page
    if (y + lines.length * fontSize * 0.5 > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
    
    doc.text(lines, margin, y);
    y += lines.length * fontSize * 0.45 + 5;
  };

  // Title
  const sunSign = data.sign || data.charts?.natal?.planets?.find((p) => p.name === 'Sun')?.sign;
  const lifePath = data.numerology?.core_numbers?.life_path?.number;
  
  addText('Astromeric Reading', 22, true);
  addText(`${data.scope.charAt(0).toUpperCase() + data.scope.slice(1)} Forecast`, 16, false);
  
  if (sunSign && lifePath) {
    addText(`${sunSign} • Life Path ${lifePath}`, 14, false);
  }
  
  y += 5;
  doc.setDrawColor(136, 192, 208);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Headline / TL;DR
  const headline = data.summary?.headline || data.theme;
  if (headline) {
    addText('Summary', 14, true);
    addText(headline, 11, false);
    y += 5;
  }

  // Sections
  if (data.sections && data.sections.length > 0) {
    for (const section of data.sections) {
      addText(section.title, 13, true);
      
      if (section.highlights && section.highlights.length > 0) {
        for (const highlight of section.highlights) {
          addText(`• ${highlight}`, 10, false);
        }
      }
      y += 3;
    }
  }

  // Numerology
  if (data.numerology?.core_numbers) {
    y += 5;
    addText('Numerology Profile', 14, true);
    
    const core = data.numerology.core_numbers;
    if (core.life_path) {
      addText(`Life Path ${core.life_path.number}: ${core.life_path.meaning || ''}`, 10, false);
    }
    if (core.expression) {
      addText(`Expression ${core.expression.number}: ${core.expression.meaning || ''}`, 10, false);
    }
    if (core.soul_urge) {
      addText(`Soul Urge ${core.soul_urge.number}: ${core.soul_urge.meaning || ''}`, 10, false);
    }
  }

  // Cycles
  if (data.numerology?.cycles) {
    y += 5;
    addText('Current Cycles', 12, true);
    
    const cycles = data.numerology.cycles;
    if (cycles.personal_year) {
      addText(`Personal Year ${cycles.personal_year.number}: ${cycles.personal_year.meaning || ''}`, 10, false);
    }
    if (cycles.personal_month) {
      addText(`Personal Month ${cycles.personal_month.number}: ${cycles.personal_month.meaning || ''}`, 10, false);
    }
    if (cycles.personal_day) {
      addText(`Personal Day ${cycles.personal_day.number}: ${cycles.personal_day.meaning || ''}`, 10, false);
    }
  }

  // Footer
  y = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by Astromeric • ${new Date().toLocaleDateString()}`, margin, y);
  doc.text('For entertainment purposes only', pageWidth - margin - 50, y);

  // Download
  const fileName = `astromeric-${data.scope}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}
